name: Build and Publish Docker Image

on:
  push:
    branches:
      - main  # Срабатывает на пуш в ветку main
  pull_request:
    branches:
      - main  # Срабатывает при PR в ветку main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '8.0.x'  # Используем .NET SDK 8.0

    - name: Build the project
      run: dotnet build Server/Server.generated.sln --configuration Release

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}  # Используем секреты для имени пользователя
        password: ${{ secrets.DOCKER_PASSWORD }}  # Используем секреты для пароля

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: ./Server
        file: ./Server/Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/server-image:latest

    - name: Logout from Docker Hub
      run: docker logout
